packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  argon2: true
  prisma: true
  "@prisma/engines": true
  "@prisma/client": true
  esbuild: true
  unrs-resolver: true
  msgpackr-extract: true
  sharp: true
  "@scarf/scarf": false
  "@tensorflow/tfjs-node": true
  core-js: false
  '@firebase/util': false
  protobufjs: false
