/**
 * Mã lỗi máy-đọc-được trả về trong field `errorCode` của API error response.
 * FE dựa vào đây để xử lý lỗi theo nhánh thay vì so sánh message.
 */
export const ERROR_CODES = {
  // chung
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  // auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_UNAUTHENTICATED: 'AUTH_UNAUTHENTICATED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_TOKEN_REUSE: 'AUTH_TOKEN_REUSE',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',
  AUTH_2FA_INVALID_CODE: 'AUTH_2FA_INVALID_CODE',
  AUTH_2FA_ALREADY_ENABLED: 'AUTH_2FA_ALREADY_ENABLED',
  AUTH_OAUTH_STATE_INVALID: 'AUTH_OAUTH_STATE_INVALID',
  AUTH_OAUTH_FAILED: 'AUTH_OAUTH_FAILED',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_USER_BANNED: 'AUTH_USER_BANNED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_INVITE_INVALID: 'AUTH_INVITE_INVALID',
  // rbac / users
  ROLE_SYSTEM_IMMUTABLE: 'ROLE_SYSTEM_IMMUTABLE',
  ROLE_NAME_TAKEN: 'ROLE_NAME_TAKEN',
  USER_SELF_ACTION_FORBIDDEN: 'USER_SELF_ACTION_FORBIDDEN',
  LAST_SUPER_ADMIN: 'LAST_SUPER_ADMIN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
