/**
 * Mã lỗi máy-đọc-được trả về trong field `errorCode` của API error response.
 * FE dựa vào đây để xử lý lỗi theo nhánh thay vì so sánh message.
 */
export const ERROR_CODES = {
  // chung
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  // auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_UNAUTHENTICATED: 'AUTH_UNAUTHENTICATED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_TOKEN_REUSE: 'AUTH_TOKEN_REUSE',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',
  AUTH_2FA_INVALID_CODE: 'AUTH_2FA_INVALID_CODE',
  AUTH_2FA_ALREADY_ENABLED: 'AUTH_2FA_ALREADY_ENABLED',
  AUTH_OAUTH_STATE_INVALID: 'AUTH_OAUTH_STATE_INVALID',
  AUTH_OAUTH_FAILED: 'AUTH_OAUTH_FAILED',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_USER_BANNED: 'AUTH_USER_BANNED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_INVITE_INVALID: 'AUTH_INVITE_INVALID',
  // rbac / users
  ROLE_SYSTEM_IMMUTABLE: 'ROLE_SYSTEM_IMMUTABLE',
  ROLE_NAME_TAKEN: 'ROLE_NAME_TAKEN',
  USER_SELF_ACTION_FORBIDDEN: 'USER_SELF_ACTION_FORBIDDEN',
  LAST_SUPER_ADMIN: 'LAST_SUPER_ADMIN',
  // multi-tenant / cơ cấu tổ chức
  ORG_CONTEXT_REQUIRED: 'ORG_CONTEXT_REQUIRED',
  ORG_SLUG_TAKEN: 'ORG_SLUG_TAKEN',
  ORG_SUSPENDED: 'ORG_SUSPENDED',
  ORG_CODE_TAKEN: 'ORG_CODE_TAKEN',
  ORGUNIT_MOVE_INTO_SELF: 'ORGUNIT_MOVE_INTO_SELF',
  ORGUNIT_HAS_CHILDREN: 'ORGUNIT_HAS_CHILDREN',
  ORGUNIT_TYPE_IN_USE: 'ORGUNIT_TYPE_IN_USE',
  // attendance / face / location
  FACE_NOT_ENROLLED: 'FACE_NOT_ENROLLED',
  FACE_NO_MATCH: 'FACE_NO_MATCH',
  FACE_SPOOF_SUSPECTED: 'FACE_SPOOF_SUSPECTED',
  FACE_QUALITY_LOW: 'FACE_QUALITY_LOW',
  FACE_MULTIPLE_FACES: 'FACE_MULTIPLE_FACES',
  FACE_NO_FACE: 'FACE_NO_FACE',
  FACE_ENGINE_UNAVAILABLE: 'FACE_ENGINE_UNAVAILABLE',
  OUT_OF_WORKSITE: 'OUT_OF_WORKSITE',
  LOCATION_REQUIRED: 'LOCATION_REQUIRED',
  FACE_REQUIRED: 'FACE_REQUIRED',
  NO_WORKSITE_ASSIGNED: 'NO_WORKSITE_ASSIGNED',
  /** Đã qua giờ tan làm → không cho chấm RA, ghi nhận quên chấm ra (HR chấm bù). */
  ATTENDANCE_AFTER_SHIFT_END: 'ATTENDANCE_AFTER_SHIFT_END',
  LEAVE_INSUFFICIENT_BALANCE: 'LEAVE_INSUFFICIENT_BALANCE',
  LEAVE_OVERLAP: 'LEAVE_OVERLAP',
  LEAVE_NO_POLICY: 'LEAVE_NO_POLICY',
  LEAVE_NOT_PENDING: 'LEAVE_NOT_PENDING',
  APPROVAL_NO_FLOW: 'APPROVAL_NO_FLOW',
  APPROVAL_NOT_YOUR_TURN: 'APPROVAL_NOT_YOUR_TURN',
  APPROVAL_ALREADY_DECIDED: 'APPROVAL_ALREADY_DECIDED',
  APPROVAL_ALREADY_PENDING: 'APPROVAL_ALREADY_PENDING',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
