import { ALL_PERMISSIONS, PERMISSIONS, type Permission } from './permissions';

/** 3 role hệ thống — seed sẵn, không xoá được (`isSystem = true`). */
export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  USER: 'USER',
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const ALL_ROLES = Object.values(ROLES) as [RoleName, ...RoleName[]];

export const ROLE_DESCRIPTIONS: Record<RoleName, string> = {
  SUPER_ADMIN: 'Toàn quyền hệ thống, không thể bị hạ quyền nếu là người cuối cùng',
  ADMIN: 'Quản trị người dùng, phiên đăng nhập và audit log',
  USER: 'Người dùng thông thường',
};

/** Map role → permissions mặc định, dùng cho seed. */
export const DEFAULT_ROLE_PERMISSIONS: Record<RoleName, Permission[]> = {
  SUPER_ADMIN: [...ALL_PERMISSIONS],
  ADMIN: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.ROLE_ASSIGN,
    PERMISSIONS.PERMISSION_READ,
    PERMISSIONS.SESSION_READ,
    PERMISSIONS.SESSION_REVOKE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.DASHBOARD_VIEW,
  ],
  USER: [PERMISSIONS.DASHBOARD_VIEW],
};

/**
 * Role org-level — tạo tự động (orgId gắn theo org, isSystem=true) khi
 * platform admin tạo Organization mới.
 */
export const ORG_ROLES = {
  ORG_ADMIN: 'ORG_ADMIN',
  HR_MANAGER: 'HR_MANAGER',
  UNIT_MANAGER: 'UNIT_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
  WORKER: 'WORKER',
} as const;

export type OrgRoleName = (typeof ORG_ROLES)[keyof typeof ORG_ROLES];

export const ALL_ORG_ROLES = Object.values(ORG_ROLES) as [
  OrgRoleName,
  ...OrgRoleName[],
];

export const ORG_ROLE_DESCRIPTIONS: Record<OrgRoleName, string> = {
  ORG_ADMIN: 'Quản trị toàn bộ tổ chức: cơ cấu, nhân sự, cấu hình, phân quyền',
  HR_MANAGER: 'Quản lý nhân sự: hồ sơ, chấm công, nghỉ phép, báo cáo toàn org',
  UNIT_MANAGER: 'Quản lý đơn vị: xem dữ liệu + duyệt đơn trong subtree mình quản lý',
  EMPLOYEE: 'Nhân viên văn phòng: tự chấm công, nghỉ phép + đăng ký/xem phiếu tăng giãn ca',
  WORKER: 'Công nhân: tự chấm công, xem công, tạo đơn nghỉ phép (không xem phiếu tăng giãn ca)',
};

/** Map role org-level → permissions mặc định khi tạo org. */
export const DEFAULT_ORG_ROLE_PERMISSIONS: Record<OrgRoleName, Permission[]> = {
  ORG_ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ORG_READ,
    PERMISSIONS.ORG_UPDATE,
    PERMISSIONS.ORGUNIT_MANAGE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.ROLE_ASSIGN,
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.SHIFT_MANAGE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_READ_ALL,
    PERMISSIONS.ATTENDANCE_CORRECT,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_REQUEST,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_MANAGE_POLICY,
    PERMISSIONS.APPROVAL_MANAGE_FLOW,
    PERMISSIONS.SHIFT_REGISTRATION_MANAGE,
    PERMISSIONS.DEVICE_MANAGE,
    PERMISSIONS.WORKSITE_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.FACE_ENROLL,
    PERMISSIONS.FACE_MANAGE,
  ],
  HR_MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ORG_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.SHIFT_MANAGE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_READ_ALL,
    PERMISSIONS.ATTENDANCE_CORRECT,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_REQUEST,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_MANAGE_POLICY,
    PERMISSIONS.SHIFT_REGISTRATION_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.FACE_ENROLL,
    PERMISSIONS.FACE_MANAGE,
  ],
  UNIT_MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ORG_READ,
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_READ_ALL,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_REQUEST,
    PERMISSIONS.SHIFT_REGISTRATION_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.FACE_ENROLL,
  ],
  // Nhân viên văn phòng: như công nhân + được đăng ký/xem phiếu tăng giãn ca
  EMPLOYEE: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ORG_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_REQUEST,
    PERMISSIONS.SHIFT_REGISTRATION_MANAGE,
    PERMISSIONS.FACE_ENROLL,
  ],
  // Công nhân: cấp thấp nhất — KHÔNG xem phiếu tăng giãn ca
  WORKER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ORG_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_REQUEST,
    PERMISSIONS.FACE_ENROLL,
  ],
};
